In [2]:

import numpy as np
import math
# СОСНЮК КАТЕРИНА ФІТ 4-6 ВАРІАНТ 22
# 1 Створіть одновимірний масив (вектор) зі значеннями 
# e^x
 
# для кожного натурального числа x, починаючи з 1, та виведіть його значення. """
# create Pandas array with dtype string
# Example 1: Use fill() function
arr = np.arange(9)
arr = list(map(lambda x: math.exp(x+1), arr))
print("Task 1")
print(arr)
# Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його тангенсами кожного натурального числа, починаючи з 1, та виведіть його значення. 


Task 1
[2.718281828459045, 7.38905609893065, 20.085536923187668, 54.598150033144236, 148.4131591025766, 403.4287934927351, 1096.6331584284585, 2980.9579870417283, 8103.083927575384]


In [3]:
# 2 Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його тангенсами кожного натурального числа, починаючи з 1, та виведіть його значення.
#Примітка: обчислено в радіанах

arr = np.arange(1,10).reshape(3, -1)

calc_tan = lambda x: math.tan(x)

arr = list(map(lambda i: list(map(lambda j: calc_tan(j), i)), arr))

print("Task 2")
print(arr)

Task 2
[[1.5574077246549023, -2.185039863261519, -0.1425465430742778], [1.1578212823495777, -3.380515006246586, -0.29100619138474915], [0.8714479827243188, -6.799711455220379, -0.45231565944180985]]


In [4]:
# 3 Створіть масив розміром 8x8, заповніть його випадковими дійсними числами від -1 до 1 та знайдіть відсоток від'ємних чисел серед всіх елементів. 
arr = np.random.uniform(-1, 1, size=(8, 8))
count=0
print(arr)
print("Task 3")
arr2 = list(map(lambda i: list(map(lambda j: globals().update(count=count+1) if (j < 0) else None, i)), arr))
print("negative numbers percentage:")
print(sum(len(l) for l in arr)*count/100)

[[ 6.56802486e-01 -3.79136879e-01  9.17721226e-01 -3.27461987e-01
  -3.47378546e-01 -1.82126729e-01 -3.25377603e-01  6.29185274e-01]
 [ 2.33061151e-01 -7.79183027e-01  5.08338118e-01 -9.89429289e-01
  -2.76427819e-01  9.63275855e-02 -2.51653693e-01  6.62160294e-01]
 [ 4.59572971e-01 -6.93040964e-01 -8.57521426e-01  7.33091748e-02
   7.73006516e-01  5.52850508e-01  4.90398785e-01  3.14734926e-01]
 [-3.52620661e-01 -4.71969332e-01 -4.52847691e-01  6.44854589e-01
  -3.02245932e-01  4.92813451e-01  6.49646557e-01  5.12901973e-01]
 [ 5.30936452e-01  7.09890327e-01 -1.35271864e-01  6.17505379e-01
   4.19181824e-01  7.56347710e-01 -5.32756957e-01  5.44261382e-01]
 [ 7.15087463e-01  3.99796826e-01  2.79404769e-01 -2.95323764e-01
  -2.04866840e-01 -3.49292486e-02 -9.42755329e-02 -9.40429895e-01]
 [ 5.89658215e-01 -1.65671905e-01  5.80540694e-01  3.20151229e-01
  -8.87717703e-01  2.77051808e-01  9.60873151e-01  9.69074210e-01]
 [ 4.18094667e-01  6.70298426e-01  3.01825585e-02 -9.16035379e-01
   

In [5]:
# 4 Створіть масив розміром 4x4, заповніть його випадковими дійсними числами від -0.8 до 0.8 та виведіть його значення
arr = np.random.uniform(-0.8, 0.8, size=(4, 4))
print("Task 4")
print(arr)


Task 4
[[-0.05369989  0.18903383  0.12381062 -0.31082598]
 [ 0.19969462 -0.77196382 -0.56699446  0.17446502]
 [-0.65273902 -0.53668304 -0.50783277  0.49316434]
 [ 0.00768426  0.59959688  0.28196381  0.15490399]]


In [6]:
# 5  Створіть два одновимірних масиви розміром 6, заповніть їх випадковими цілими числами
# в діапазоні від 5 до 15 та виконайте на них поелементні операції додавання,
# віднімання та множення. 
arr1 = np.random.randint(5, 15, size=(6))
arr2 = np.random.randint(5, 15, size=(6))
print("Task 5")
print("Initial arrays")
print(arr1)
print(arr2)
arr3 = [x+y for x, y in zip(arr1, arr2)]
print("Result of addition")
print(arr3)
arr4 = [x-y for x, y in zip(arr1, arr2)]
print("Result of substraction")
print(arr4)
print("Result of multiplication")
arr5 = [x*y for x, y in zip(arr1, arr2)]
print(arr5)

Task 5
Initial arrays
[ 6  8 12  7  6 11]
[12  7  7 11 10 10]
Result of addition
[18, 15, 19, 18, 16, 21]
Result of substraction
[-6, 1, 5, -4, -4, 1]
Result of multiplication
[72, 56, 84, 77, 60, 110]


In [7]:
# 6 Створіть два вектори розміром 7, заповніть їх довільними цілими числами та знайдіть їх скалярний добуток.
print("Task 6")
arr1 = np.random.randint(-1000, 1000, size=(7))
arr2 = np.random.randint(-1000, 1000, size=(7))
print("Initial arrays")
print(arr1)
print(arr2)
arr3 = np.dot(arr1, arr2) 
print("Scalar multiplication")
print(arr3)


Task 6
Initial arrays
[ 789 -750 -426  247 -618  650 -418]
[ 642 -133  352 -288  801 -799 -116]
Scalar multiplication
-580680


In [8]:
# 7 Створіть дві матриці розміром 3x2 та 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 8 та перемножте їх між собою. 
arr1 = np.random.randint(1, 8, size=(3, 2))
arr2 = np.random.randint(1, 8, size=(2, 2))
print("Initial arrays")
print(arr1)
print(arr2)
print("Task 7")
arr3 = np.matmul(arr1, arr2)
print(arr3)

Initial arrays
[[4 4]
 [4 1]
 [7 5]]
[[2 4]
 [2 2]]
Task 7
[[16 24]
 [10 18]
 [24 38]]


In [9]:
# 8 Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 8 та знайдіть її обернену матрицю. 
arr = np.random.randint(1, 8, size=(3, 3))
inv = np.linalg.inv(arr)
print("Task 8")
print("Initial matrix")
print(arr)
print("Inverted matrix")
print(inv)

Task 8
Initial matrix
[[4 1 7]
 [4 5 1]
 [7 6 7]]
Inverted matrix
[[ 1.61111111  1.94444444 -1.88888889]
 [-1.16666667 -1.16666667  1.33333333]
 [-0.61111111 -0.94444444  0.88888889]]


In [10]:
# 9 Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від -1 до 1 та транспонуйте її. 
arr = np.random.uniform(-1, 1, size=(4, 4))
transp = np.transpose(arr)
print("Task 9")
print("Initial matrix")
print(arr)
print("Transposed matrix")
print(transp)

Task 9
Initial matrix
[[-0.68331941 -0.48492026  0.4275273  -0.50513151]
 [ 0.04574007  0.63031751  0.77384108  0.26107119]
 [ 0.36548514  0.55259194  0.21259365  0.08939808]
 [-0.90964644  0.11950484 -0.93582639  0.9984274 ]]
Transposed matrix
[[-0.68331941  0.04574007  0.36548514 -0.90964644]
 [-0.48492026  0.63031751  0.55259194  0.11950484]
 [ 0.4275273   0.77384108  0.21259365 -0.93582639]
 [-0.50513151  0.26107119  0.08939808  0.9984274 ]]


In [15]:
# 10 Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть матрицю випадковими дійсними числами від 0 до 1, 
# а вектор - випадковими цілими числами в діапазоні від 1 до 10,
# і знайдіть суму добутків елементів кожного стовпця матриці на відповідний елемент вектору. 
matrix = np.random.uniform(0, 1, size=(3, 4))
vector = np.random.randint(1, 10, size=(4))
print("Task 10")
print("Initial matrix")
print(matrix)
print("Initial vector")
print(vector)
result = np.sum(matrix * vector, axis=0)
print("Multiplications sum")
print(np.sum(result))

Task 10
Initial matrix
[[0.20230548 0.81945079 0.25164532 0.86027153]
 [0.57803835 0.67917645 0.36160523 0.45370552]
 [0.58340577 0.6597177  0.12377694 0.78549569]]
Initial vector
[3 9 5 4]
Multiplications sum
35.599381666210796


In [18]:
# 11 Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть матрицю випадковими цілими числами в діапазоні від 1 до 10, 
# а вектор - випадковими дійсними числами від 0 до 1, 
# і знайдіть суму добутків елементів кожного стовпця матриці на відповідний елемент вектору. 
matrix = np.random.randint(1, 10, size=(2, 3))
vector = np.random.uniform(0, 1, size=(3))
print("Task 11")
print("Initial matrix")
print(matrix)
print("Initial vector")
print(vector)
result = np.sum(matrix * vector, axis=0)
print("Multiplications sum")
print(np.sum(result))

Task 11
Initial matrix
[[3 7 7]
 [6 6 1]]
Initial vector
[0.13204264 0.13667195 0.02884339]
Multiplications sum
3.1958662756586214


In [20]:
# 12 Створіть дві матриці розміром 7x7, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та 
# знайдіть суму всіх елементів другої матриці. 
matrix1 = np.random.randint(1, 10, size=(7, 7))
matrix2= np.random.randint(1, 10, size=(7, 7))
sum = np.sum(matrix2)
print("Task 12")
print("Initial matrix 1")
print(matrix1)
print("Initial matrix 2")
print(matrix2)
print(sum)

Task 12
Initial matrix 1
[[8 8 1 5 8 7 9]
 [3 2 3 5 4 5 8]
 [6 9 1 9 7 9 6]
 [8 9 6 7 7 4 3]
 [2 9 7 9 2 4 4]
 [2 5 3 6 6 5 1]
 [4 8 2 7 4 7 2]]
Initial matrix 2
[[9 1 4 3 2 9 4]
 [8 9 4 3 8 1 7]
 [7 6 2 6 6 4 3]
 [3 9 8 5 4 3 2]
 [4 7 2 3 2 2 6]
 [3 6 6 3 6 7 6]
 [2 3 4 8 5 6 3]]
234


In [23]:
# 13 Створіть дві матриці розміром 6x6, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть суму їх елементів. 
matrix1 = np.random.randint(1, 10, size=(6, 6))
matrix2= np.random.randint(1, 10, size=(6, 6))
sum = np.sum(matrix1) + np.sum(matrix2)
print("Task 13")
print("Initial matrix 1")
print(matrix1)
print("Initial matrix 2")
print(matrix2)
print(sum)

Task 12
Initial matrix 1
[[9 8 6 4 5 2]
 [7 8 3 2 2 4]
 [2 4 4 5 7 9]
 [6 8 7 6 8 8]
 [3 4 6 4 2 4]
 [4 2 1 5 5 7]]
Initial matrix 2
[[4 6 8 6 2 9]
 [3 4 2 9 6 6]
 [6 1 1 5 7 5]
 [2 4 9 1 3 3]
 [6 7 4 8 4 8]
 [3 1 2 1 6 2]]
345


In [24]:
# 14 Створіть матрицю розміром 8x8, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів на головній діагоналі. 
matrix = np.random.randint(1, 100, size=(8, 8))
print("Task 14")
print("Initial matrix")
print(matrix)
result = np.trace(matrix)
print(result)


Task 14
Initial matrix
[[89 68 58 30  1  6 81 68]
 [75 39 54 11 56 76 49 95]
 [ 9 28 40 24 32 78 93 97]
 [69 53 84 47 71 67 28 50]
 [93 17  7 84 72 38  5 53]
 [64 63  9 13 61 56 49 85]
 [44 80 43  7 83 78 74 36]
 [85 93 76 49 91 25 83 37]]
454


In [30]:
# 15 Створіть матрицю розміром 8x8, заповніть її випадковими дійсними числами в діапазоні від -1 до 1 та 
# знайдіть вектор-стовпчик, що містить добуток елементів кожного стовпця матриці. 
matrix = np.random.uniform(-1, 1, size=(8, 8))
print("Task 15")
print("Initial matrix")
print(matrix)
column_mul = np.prod(matrix, axis=0)
column_vect = column_mul.reshape(-1, 1)
print("Vector containing the multiplication of elements in each column:")
print(column_vect)

Task 15
Initial matrix
[[ 0.28488153  0.90479176  0.46948785 -0.07415687 -0.26435309 -0.70743175
  -0.58058661  0.40582842]
 [-0.36312787  0.23153008 -0.14940648  0.051698    0.46892664 -0.92349337
   0.4220638  -0.41582927]
 [ 0.29161829  0.34671783 -0.66590166  0.25012768  0.86542859 -0.26990375
  -0.51401745 -0.24694238]
 [-0.55896398 -0.49675489  0.07201539 -0.74234526 -0.33452213 -0.35854869
  -0.01011716 -0.92950001]
 [ 0.38300711  0.64396829 -0.03035455  0.62968611 -0.89937344 -0.51972326
  -0.5741772   0.28440188]
 [ 0.34269617 -0.99054738  0.75447206  0.71044855 -0.84578731  0.82736742
   0.04819601 -0.82207599]
 [ 0.40087859  0.24460902  0.57786187 -0.40858249 -0.86100899  0.00953606
  -0.01755463 -0.68241016]
 [ 0.21477713 -0.91304243  0.33676366 -0.39326088  0.88016437 -0.22034352
  -0.81896235 -0.730768  ]]
Vector containing the multiplication of elements in each column:
[[ 1.90563384e-04]
 [-5.14017082e-03]
 [-1.49915120e-05]
 [ 5.11693739e-05]
 [-2.06879798e-02]
 [ 5.712

In [2]:
# Висновок: в процесі виконання лабораторної роботи я більш досконало вивчила можливості бібліотеки numpy, що стосуються лінійної алгебри.
# Окремим завданням я поставила для себе мінімально використовувати цикли та максимально - можливості бібліотеки, адже так код є більш валідним
# та виконується швидше (особливо актуально через специфіку мови python)